Version: 0.3.7
CompanyName: Vermeil
FileDescription: MSFONT
InternalName: MSFONT
LegalCopyright: MIT LICENSE.
OriginalFilename: MSFONT.exe
ProductName: MSFONT
Translation:
  - langID: 0
    charsetID: 1200
  - langID: 1033
    charsetID: 1252