# Define the name of the workflow
name: Build, Upload, and Run MSFONT Windows

# Trigger the workflow when code is pushed to the "experimental" branch
on:
  push:
    branches:
      - experimental

# Define the jobs to be executed as part of this workflow
jobs:
  # Define the "build" job
  build:
    # Specify that this job should run on a Windows environment
    runs-on: windows-latest

    # Define the steps to be executed within the job
    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v4.0.0

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4.7.0
      with:
        python-version: 3.11.5

    # Step 3: Install Python dependencies from requirements.txt
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: ${{ github.workspace }}

    # Step 4: Check and update outdated Python packages
    - name: Check and Update Python packages
      run: |
        python -m pip list --outdated
        python -m pip install --upgrade $(python -m pip list --outdated | awk '{print $1}' | tail -n +3)
      working-directory: ${{ github.workspace }}

    # Step 5: Build the MSFONT application using PyInstaller
    - name: Build MSFONT
      run: |
        pyinstaller --noconfirm --onedir --console --icon "Assets/ICON/Sv-001.ico" --name "MSFONT" --version-file "pyinstaller/version_msfont.txt" --add-data "src/main.py;." --add-data "Assets;Assets/"  "src/terminal.py"

    # Step 6: Build the UPDATER application using PyInstaller
    - name: Build UPDATER
      run: |
        pyinstaller --noconfirm --onefile --console --icon "Assets/ICON/Sv-001-UPDATER.ico" --name "UPDATER" --version-file "pyinstaller/version_updater.txt"  "src/auto_updater.py"

    # Step 7: Upload the built artifacts for MSFONT
    - name: Upload MSFONT artifacts
      uses: actions/upload-artifact@v3.1.3
      with:
        name: MSFONT
        path: dist/MSFONT

    # Step 8: Upload the built artifacts for UPDATER
    - name: Upload UPDATER artifacts
      uses: actions/upload-artifact@v3.1.3
      with:
        name: UPDATER
        path: dist/UPDATER.exe


