name: Build Upload MSFONT

on:
  push:
    branches:
      - experimental

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.0

    - name: Set up Python
      uses: actions/setup-python@v4.7.1
      with:
        python-version: 3.11.5

    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt
      working-directory: ${{ github.workspace }}

    - name: Build MSFONT
      run: |
        pyinstaller --noconfirm --onedir --windowed --icon "Assets/ICON/Sv-002.ico" --name "MSFONT" --version-file "Other/version_msfont.txt" --add-data "C:\Users\$env:USERNAME\AppData\Roaming\Python\Python311\site-packages/customtkinter;customtkinter/" --add-data "src/main.py;." --add-data "Assets:Assets/"  "src/ui.py"

    - name: Build UPDATER
      run: |
        pyinstaller --noconfirm --onedir --windowed --icon "Assets/ICON/Sv-002-UPDATER.ico" --name "UPDATER" --version-file "Other/version_updater.txt" --add-data "C:\Users\$env:USERNAME\AppData\Roaming\Python\Python311\site-packages/customtkinter;customtkinter/"  "src/update.py"

    - name: Move Assets folder
      run: |
        mv dist/MSFONT/_internal/Assets dist/MSFONT/
      shell: bash

    - name: Upload MSFONT artifacts
      uses: actions/upload-artifact@v3.1.3
      with:
        name: MSFONT
        path: dist/MSFONT
